[project]
name = "manta-ray-client"
version = "2.0.1"
description = "Python API and helper scripts to interact with the MWA ASVO."
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "colorama>=0.4.6",
    "requests>=2.18.3",
    "urllib3>=2.7.0",
    "websocket-client>=1.8.0",
]

[project.scripts]
mwa_client = "mantaray.scripts.mwa_client:main"

[tool.hatch.build.targets.wheel]
packages = ["mantaray"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"