[pytests]
minversion = 8.0
addopts =
    -ra
    -q
    --strict-markers
    --cov=mwa_cli
    --cov-report=html
    --cov-report=term-missing:skip-covered
testpaths = tests
asyncio_mode = auto
markers =
    integration
