# generated by datamodel-codegen:
#   filename:  tmpzpq_e28q.json
#   timestamp: 2026-08-05T06:59:18+00:00

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, EmailStr, Field, RootModel


class ApiLoginRequest(BaseModel):
    """
    Request model for client app login endpoint (uses API key instead of username)
    """

    login: str = Field(
        ...,
        examples=['manta-ray-clientv2.0.1', 'giant-squidv2.0.1'],
        max_length=36,
        min_length=1,
        title='Login',
    )
    """
    The name of the client app
    """
    password: str = Field(..., title='Password')


class AuthStatusResponse(BaseModel):
    authenticated: bool = Field(..., title='Authenticated')


class JobType(Enum):
    download = 'download'
    voltage = 'voltage'
    conversion = 'conversion'
    beamformer = 'beamformer'
    imaging = 'imaging'


class Delivery(RootModel[str]):
    root: str = Field('acacia', pattern='^(acacia|scratch|dug)$', title='Delivery')


class DeliveryFormat(RootModel[str]):
    root: str = Field('files', pattern='^(tar|files)$', title='Delivery Format')


class UserPawseyGroup(Enum):
    mwaops = 'mwaops'
    mwaasvo = 'mwaasvo'
    mwavcs = 'mwavcs'
    mwaeor = 'mwaeor'
    mwaasci = 'mwaasci'


class Mode(Enum):
    mwax_beamformer = 'MWAX_BEAMFORMER'
    mwax_corr_bf = 'MWAX_CORR_BF'


class BeamformerJobParams(BaseModel):
    """
    Parameters for beamformer job submission
    """

    obs_id: int = Field(..., ge=888888889, title='Obs Id')
    job_type: JobType = Field(..., title='Job Type')
    delivery: Delivery | None = Field('acacia', title='Delivery', validate_default=True)
    delivery_format: DeliveryFormat | None = Field(
        'files', title='Delivery Format', validate_default=True
    )
    user_pawsey_group: UserPawseyGroup = Field(..., title='User Pawsey Group')
    user_dug_group: str = Field(
        ..., pattern='/^mwa (gleam|eor)$/i', title='User Dug Group'
    )
    mode: Mode | None = Field('MWAX_BEAMFORMER', title='Mode')


class Output(Enum):
    ms = 'ms'
    uvfits = 'uvfits'


class Delivery1(Enum):
    acacia = 'acacia'
    scratch = 'scratch'


class DeliveryFormat1(Enum):
    tar = 'tar'
    files = 'files'


class AvgTimeRes(RootModel[float]):
    root: float = Field(2.0, ge=0.0, title='Avg Time Res')


class AvgFreqRes(RootModel[float]):
    root: float = Field(40.0, ge=0.0, le=1280.0, title='Avg Freq Res')


class FlagEdgeWidth(RootModel[float]):
    root: float = Field(80.0, ge=0.0, le=640.0, title='Flag Edge Width')


class Centre(Enum):
    phase = 'phase'
    pointing = 'pointing'
    custom = 'custom'


class PhaseCentreRa(RootModel[float]):
    root: float = Field(..., ge=0.0, le=359.999999, title='Phase Centre Ra')


class PhaseCentreDec(RootModel[float]):
    root: float = Field(..., ge=-90.0, le=90.0, title='Phase Centre Dec')


class ConversionJobParams(BaseModel):
    """
    Parameters for conversion job submission
    """

    obs_id: int = Field(..., ge=888888889, title='Obs Id')
    job_type: JobType = Field(..., title='Job Type')
    output: Output | None = Field('ms', title='Output')
    delivery: Delivery1 | None = Field('acacia', title='Delivery')
    delivery_format: DeliveryFormat1 | None = Field('files', title='Delivery Format')
    user_pawsey_group: UserPawseyGroup = Field(..., title='User Pawsey Group')
    avg_time_res: AvgTimeRes | None = Field(
        2.0, title='Avg Time Res', validate_default=True
    )
    avg_freq_res: AvgFreqRes | None = Field(
        40.0, title='Avg Freq Res', validate_default=True
    )
    flag_edge_width: FlagEdgeWidth | None = Field(
        80.0, title='Flag Edge Width', validate_default=True
    )
    centre: Centre | None = Field('phase', title='Centre')
    phase_centre_ra: PhaseCentreRa | None = Field(..., title='Phase Centre Ra')
    phase_centre_dec: PhaseCentreDec | None = Field(..., title='Phase Centre Dec')
    apply_di_cal: bool | None = Field(False, title='Apply Di Cal')
    no_geometry_delay: bool | None = Field(False, title='No Geometry Delay')
    no_digital_gains: bool | None = Field(False, title='No Digital Gains')
    no_flag_dc: bool | None = Field(False, title='No Flag Dc')
    no_passband_gains: bool | None = Field(False, title='No Passband Gains')


class Delivery2(Enum):
    acacia = 'acacia'
    scratch = 'scratch'
    dug = 'dug'


class DownloadType(Enum):
    vis = 'vis'
    meta = 'meta'


class DownloadJobParams(BaseModel):
    """
    Parameters for download job submission
    """

    obs_id: int = Field(..., ge=888888889, title='Obs Id')
    job_type: JobType = Field(..., title='Job Type')
    delivery: Delivery2 | None = Field('acacia', title='Delivery')
    delivery_format: DeliveryFormat1 | None = Field('files', title='Delivery Format')
    download_type: DownloadType | None = Field('vis', title='Download Type')
    user_pawsey_group: UserPawseyGroup = Field(..., title='User Pawsey Group')
    user_dug_group: str = Field(
        ..., pattern='/^mwa (gleam|eor)$/i', title='User Dug Group'
    )


class FieldError(BaseModel):
    """
    Field-specific validation error
    """

    field: str = Field(..., title='Field')
    """
    Field name that failed valiation
    """
    message: str = Field(..., title='Message')
    """
    Error message for this field
    """


class HealthResponse(BaseModel):
    """
    Health check response model
    """

    status: str = Field(..., title='Status')
    service: str = Field(..., title='Service')
    version: str = Field(..., title='Version')
    database: str = Field(..., title='Database')


class Delivery3(RootModel[str]):
    root: str = Field('acacia', pattern='^(acacia|scratch|dug)$', title='Delivery')


class DeliveryFormat3(RootModel[str]):
    root: str = Field('files', pattern='^(tar|files)$', title='Delivery Format')


class PhaseCenter(Enum):
    phase = 'phase'
    custom = 'custom'


class CustomRa(RootModel[float]):
    root: float = Field(..., ge=0.0, le=359.999999, title='Custom Ra')


class CustomDec(RootModel[float]):
    root: float = Field(..., ge=-90.0, le=90.0, title='Custom Dec')


class ImageSize(IntEnum):
    integer_512 = 512
    integer_1024 = 1024
    integer_2048 = 2048
    integer_3072 = 3072
    integer_4096 = 4096
    integer_8192 = 8192


class Weighting(Enum):
    briggs = 'briggs'
    uniform = 'uniform'
    natural = 'natural'


class Robust(RootModel[float]):
    root: float = Field(-0.5, ge=-2.0, le=2.0, title='Robust')


class CleanIterations(RootModel[int]):
    root: int = Field(100000, le=1000000, title='Clean Iterations')


class AbsThreshold(RootModel[float]):
    root: float = Field(0.001, ge=0.0, le=10.0, title='Abs Threshold')


class CleanThreshold(RootModel[float]):
    root: float = Field(..., ge=0.0, le=10.0, title='Clean Threshold')


class AutoThreshold(RootModel[float]):
    root: float = Field(0.5, ge=0.1, le=5.0, title='Auto Threshold')


class Nmiter(RootModel[int]):
    root: int = Field(10, ge=1, le=500, title='Nmiter')


class Mgain(RootModel[float]):
    root: float = Field(0.8, ge=0.1, le=1.0, title='Mgain')


class AutoMask(RootModel[int]):
    root: int = Field(3, ge=32, le=512, title='Auto Mask')


class Nwlayers(RootModel[int]):
    root: int = Field(..., ge=32, le=512, title='Nwlayers')


class UvwMin(RootModel[float]):
    root: float = Field(75, le=100.0, title='Uvw Min')


class UvwMax(RootModel[float]):
    root: float = Field(..., ge=1.0, le=5000.0, title='Uvw Max')


class InputMode(Enum):
    raw = 'raw'
    processed = 'processed'


class OutputMode(Enum):
    fits = 'fits'
    all_fits = 'all_fits'
    all_files = 'all_files'


class ImagingJobParams(BaseModel):
    """
    Parameters for image job submission
    """

    obs_id: int = Field(..., ge=888888889, title='Obs Id')
    job_type: JobType = Field(..., title='Job Type')
    delivery: Delivery3 | None = Field(
        'acacia', title='Delivery', validate_default=True
    )
    delivery_format: DeliveryFormat3 | None = Field(
        'files', title='Delivery Format', validate_default=True
    )
    user_pawsey_group: UserPawseyGroup = Field(..., title='User Pawsey Group')
    user_dug_group: str = Field(
        ..., pattern='/^mwa (gleam|eor)$/i', title='User Dug Group'
    )
    apply_di_cal: bool | None = Field(True, title='Apply Di Cal')
    avg_time_res: AvgTimeRes | None = Field(
        2.0, title='Avg Time Res', validate_default=True
    )
    avg_freq_res: AvgFreqRes | None = Field(
        40.0, title='Avg Freq Res', validate_default=True
    )
    flag_edge_width: FlagEdgeWidth | None = Field(
        80.0, title='Flag Edge Width', validate_default=True
    )
    phase_center: PhaseCenter | None = Field('phase', title='Phase Center')
    custom_ra: CustomRa | None = Field(..., title='Custom Ra')
    custom_dec: CustomDec | None = Field(..., title='Custom Dec')
    image_size: ImageSize | None = Field(3072, title='Image Size')
    pixel_scale: float = Field(..., ge=10.0, le=120.0, title='Pixel Scale')
    weighting: Weighting | None = Field('briggs', title='Weighting')
    robust: Robust | None = Field(-0.5, title='Robust', validate_default=True)
    clean_iterations: CleanIterations | None = Field(
        100000, title='Clean Iterations', validate_default=True
    )
    abs_threshold: AbsThreshold | None = Field(
        0.001, title='Abs Threshold', validate_default=True
    )
    clean_threshold: CleanThreshold | None = Field(..., title='Clean Threshold')
    auto_threshold: AutoThreshold | None = Field(
        0.5, title='Auto Threshold', validate_default=True
    )
    nmiter: Nmiter | None = Field(10, title='Nmiter', validate_default=True)
    mgain: Mgain | None = Field(0.8, title='Mgain', validate_default=True)
    auto_mask: AutoMask | None = Field(3, title='Auto Mask', validate_default=True)
    apply_primary_beam: bool | None = Field(True, title='Apply Primary Beam')
    nwlayers: Nwlayers | None = Field(..., title='Nwlayers')
    wstack_nwlayers: int | None = Field(..., title='Wstack Nwlayers')
    multiscale: bool | None = Field(False, title='Multiscale')
    uvw_min: UvwMin | None = Field(75, title='Uvw Min', validate_default=True)
    uvw_max: UvwMax | None = Field(..., title='Uvw Max')
    join_polarizations: bool | None = Field(False, title='Join Polarizations')
    channels_out: int | None = Field(4, title='Channels Out')
    join_channels: bool | None = Field(True, title='Join Channels')
    pol: str | None = Field('XX,YY', title='Pol')
    input_mode: InputMode | None = Field('raw', title='Input Mode')
    output_mode: OutputMode | None = Field('fits', title='Output Mode')


class JobDetailResponse(BaseModel):
    """
    Complete job details response
    """

    id: int = Field(..., title='Id')
    """
    Unique job identifier
    """
    user_id: int = Field(..., title='User Id')
    """
    ID of user who submitted the job
    """
    job_type: int = Field(..., title='Job Type')
    """
    Job type: 0=Conversion, 1=Download, 3=Voltage, 5=Beamformer, 6=Imaging
    """
    job_state: str = Field(..., title='Job State')
    """
    Current job state: 0=Queued, 1=WaitCal 2=Staging, 3=Staged, 4=Downloading, 5=Preprocessing, 6=Delivering, 9=Completed, 10=Error, 11=Cancelled
    """
    job_params: dict[str, Any] = Field(..., title='Job Params')
    """
    Job parameters as JSON object (obs_id, delivery, processing options)
    """
    product: dict[str, Any] | None = Field(None, title='Product')
    """
    Job output/results when completed (file listings, download links)
    """
    created: AwareDatetime = Field(..., title='Created')
    """
    Timestamp when job was created
    """
    started: AwareDatetime | None = Field(..., title='Started')
    """
    Timestamp of when the job began processing
    """
    completed: AwareDatetime | None = Field(..., title='Completed')
    """
    Timestamp when job completed (null if still processing)
    """
    modified: AwareDatetime | None = Field(..., title='Modified')
    """
    Timestamp of when the job was last modified
    """
    error_text: str | None = Field(None, title='Error Text')
    """
    Error message if job failed (null if no error)
    """
    first_name: str = Field(..., title='First Name')
    """
    First name of user who submitted the job
    """
    last_name: str = Field(..., title='Last Name')
    """
    Last name of user who submitted the job
    """


class Days(RootModel[int]):
    root: int = Field(30, gt=1, le=30, title='Days')
    """
    return the past x number of days when querying db
    """


class JobsByUserRequest(BaseModel):
    """
    Parameters for /job_history endpoint
    """

    days: Days | None = Field(30, title='Days', validate_default=True)
    """
    return the past x number of days when querying db
    """
    limit: int | None = Field(100, gt=0, le=500, title='Limit')
    """
    maximum number of records to return
    """
    offset: int | None = Field(0, ge=0, title='Offset')
    """
    the offset (used to paginate the query results)
    """
    job_state: str | None = Field(None, title='Job State')
    job_type: int | None = Field(None, title='Job Type')
    date_from: AwareDatetime | None = Field(None, title='Date From')
    date_to: AwareDatetime | None = Field(None, title='Date To')
    sort_by: str | None = Field('id', title='Sort By')


class JobsByUserResponse(BaseModel):
    """
    Parameters for /job_history endpoint
    """

    jobs: list[dict[str, Any]] = Field(..., title='Jobs')
    """
    List of jobs pertaining to a specific user
    """
    total_count: int = Field(..., title='Total Count')
    """
    The total number of jobs
    """


class TokenResponse(BaseModel):
    """
    Response model for token-issuing endpoints (login, refresh)
    """

    access_token: str = Field(..., title='Access Token')
    """
    JWT access token (also set in HTTP-only cookie)
    """
    refresh_token: str = Field(..., title='Refresh Token')
    """
    JWT refresh token (also set in HTTP-only cookie)
    """
    token_type: str | None = Field('bearer', title='Token Type')
    """
    Token type for Authorization header
    """


class UserLoginRequest(BaseModel):
    """
    Request model for login endpoint
    """

    username: str = Field(
        ..., examples=['john_doe'], max_length=16, min_length=1, title='Username'
    )
    """
    Username or email address
    """
    password: str = Field(
        ...,
        examples=['securePassword123!'],
        max_length=16,
        min_length=1,
        title='Password',
    )
    """
    User password
    """


class UserLogoutResponse(BaseModel):
    """
    Response model for logout endpoint
    """

    message: str | None = Field('Logged out successfully', title='Message')
    """
    success message
    """


class UserProfile(BaseModel):
    id: int = Field(..., title='Id')
    login: str = Field(..., title='Login')
    email: EmailStr | None = Field(None, title='Email')
    first_name: str | None = Field(None, title='First Name')
    last_name: str | None = Field(None, title='Last Name')
    is_superuser: bool | None = Field(False, title='Is Superuser')
    pawsey_group: str | None = Field(None, title='Pawsey Group')
    dug_group: str | None = Field(None, title='Dug Group')
    provider_id: int | None = Field(None, title='Provider Id')
    created: AwareDatetime | None = Field(None, title='Created')
    disabled: bool | None = Field(True, title='Disabled')
    confirmed: bool | None = Field(False, title='Confirmed')


class UserRegistrationRequest(BaseModel):
    """
    Request model for registration endpoint
    """

    username: str = Field(..., max_length=100, min_length=3, title='Username')
    password: str = Field(..., min_length=8, title='Password')
    retypepassword: str = Field(..., min_length=8, title='Retypepassword')
    firstname: str = Field(..., title='Firstname')
    lastname: str = Field(..., title='Lastname')
    email: EmailStr = Field(..., title='Email')
    affiliation: str = Field(..., title='Affiliation')
    orcid: str | None = Field(..., title='Orcid')
    confirmed: bool | None = Field(False, title='Confirmed')
    disabled: bool | None = Field(True, title='Disabled')
    subscribed_to_status_emails: bool | None = Field(
        False, title='Subscribed To Status Emails'
    )
    provider_id: int | None = Field(1, title='Provider Id')


class UserResponse(BaseModel):
    """
    Response model for user information
    """

    id: int = Field(..., title='Id')
    """
    User ID
    """
    login: str = Field(..., title='Login')
    """
    username
    """
    email: EmailStr = Field(..., title='Email')
    """
    user email address
    """
    is_superuser: bool = Field(..., title='Is Superuser')
    """
    whether user has admin privileges
    """
    pawsey_group: str | None = Field(None, title='Pawsey Group')
    """
    Pawsey group membership
    """
    dug_group: str | None = Field(None, title='Dug Group')
    """
    DUG group membership
    """


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class Delivery4Enum(Enum):
    scratch = 'scratch'


class Delivery4(RootModel[Delivery4Enum | None]):
    root: Delivery4Enum | None = Field('scratch', title='Delivery')


class DeliveryFormat4Enum(Enum):
    files = 'files'


class DeliveryFormat4(RootModel[DeliveryFormat4Enum | None]):
    root: DeliveryFormat4Enum | None = Field('files', title='Delivery Format')


class FromChannel(RootModel[int]):
    root: int = Field(..., ge=0, le=255, title='From Channel')


class ToChannel(RootModel[int]):
    root: int = Field(..., ge=0, le=255, title='To Channel')


class VoltageJobParams(BaseModel):
    """
    Parameters for voltage job submission
    """

    obs_id: int = Field(..., ge=888888889, title='Obs Id')
    job_type: JobType = Field(..., title='Job Type')
    delivery: Delivery4 | None = Field(
        'scratch', title='Delivery', validate_default=True
    )
    delivery_format: DeliveryFormat4 | None = Field(
        'files', title='Delivery Format', validate_default=True
    )
    user_pawsey_group: UserPawseyGroup = Field(..., title='User Pawsey Group')
    offset: int = Field(..., ge=0, le=5400, title='Offset')
    duration: int = Field(..., ge=0, title='Duration')
    channel_range: bool | None = Field(False, title='Channel Range')
    from_channel: FromChannel | None = Field(None, title='From Channel')
    to_channel: ToChannel | None = Field(None, title='To Channel')


class WebSocketTokenResponse(BaseModel):
    """
    Response model for token-issuing endpoint (/v2/ws/jobs)
    """

    token: str = Field(..., title='Token')
    """
    JWT websocket token
    """


class ApiLoginResponse(BaseModel):
    """
    Response model for login endpoint through other clients (CLIs, external services)
    """

    access_token: str = Field(..., title='Access Token')
    """
    JWT access token (also set in HTTP-only cookie)
    """
    refresh_token: str = Field(..., title='Refresh Token')
    """
    JWT refresh token (also set in HTTP-only cookie)
    """
    token_type: str | None = Field('bearer', title='Token Type')
    """
    Token type for Authorization header
    """
    user: UserResponse


class ErrorResponse(BaseModel):
    """
    Standard error response structure for all ASVO API endpoints
    """

    error_code: str = Field(..., title='Error Code')
    """
    machine readable error code
    """
    message: str = Field(..., title='Message')
    """
    user friendly error message
    """
    detail: str | None = Field(None, title='Detail')
    """
    Additional technical detail
    """
    suggestion: str | None = Field(None, title='Suggestion')
    """
    Suggested resolution
    """
    field_errors: list[FieldError] | None = Field(None, title='Field Errors')
    """
    Field-specific validation errors
    """
    request_id: str | None = Field(None, title='Request Id')
    """
    Request ID for tracing
    """


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')
