# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-06-16T07:13:35+00:00

from __future__ import annotations

from typing import Any

from pydantic import AwareDatetime, BaseModel, EmailStr, Field, RootModel


class AuthStatusResponse(BaseModel):
    authenticated: bool = Field(..., title="Authenticated")


class Delivery(RootModel[str]):
    root: str = Field("acacia", pattern="^(acacia|scratch|dug)$", title="Delivery")


class DeliveryFormat(RootModel[str]):
    root: str = Field("files", pattern="^(tar|files)$", title="Delivery Format")


class BeamformerJobParams(BaseModel):
    """
    Parameters for beamformer job submission
    """

    obs_id: int = Field(..., ge=888888889, title="Obs Id")
    job_type: str = Field(..., title="Job Type")
    delivery: Delivery | None = Field("acacia", title="Delivery", validate_default=True)
    delivery_format: DeliveryFormat | None = Field(
        "files", title="Delivery Format", validate_default=True
    )
    user_pawsey_group: str = Field(..., title="User Pawsey Group")
    user_dug_group: str = Field(..., pattern="/^mwa (gleam|eor)$/i", title="User Dug Group")
    mode: str | None = Field("MWAX_BEAMFORMER", title="Mode")


class AvgTimeRes(RootModel[float]):
    root: float = Field(2.0, ge=0.0, title="Avg Time Res")


class AvgFreqRes(RootModel[float]):
    root: float = Field(40.0, ge=0.0, title="Avg Freq Res")


class FlagEdgeWidth(RootModel[float]):
    root: float = Field(80.0, ge=0.0, title="Flag Edge Width")


class ConversionJobParams(BaseModel):
    """
    Parameters for conversion job submission
    """

    obs_id: int = Field(..., ge=888888889, title="Obs Id")
    job_type: str = Field(..., title="Job Type")
    output: str | None = Field("ms", title="Output")
    delivery: str | None = Field("acacia", title="Delivery")
    delivery_format: str | None = Field("files", title="Delivery Format")
    user_pawsey_group: str = Field(..., title="User Pawsey Group")
    avg_time_res: AvgTimeRes | None = Field(2.0, title="Avg Time Res", validate_default=True)
    avg_freq_res: AvgFreqRes | None = Field(40.0, title="Avg Freq Res", validate_default=True)
    flag_edge_width: FlagEdgeWidth | None = Field(
        80.0, title="Flag Edge Width", validate_default=True
    )
    centre: str | None = Field("phase", title="Centre")
    phase_centre_ra: float | None = Field(..., title="Phase Centre Ra")
    phase_centre_dec: float | None = Field(..., title="Phase Centre Dec")
    apply_di_cal: bool | None = Field(False, title="Apply Di Cal")
    no_geometry_delay: bool | None = Field(False, title="No Geometry Delay")
    no_digital_gains: bool | None = Field(False, title="No Digital Gains")
    no_flag_dc: bool | None = Field(False, title="No Flag Dc")
    no_passband_gains: bool | None = Field(False, title="No Passband Gains")


class DownloadJobParams(BaseModel):
    """
    Parameters for download job submission
    """

    obs_id: int = Field(..., ge=888888889, title="Obs Id")
    job_type: str = Field(..., title="Job Type")
    delivery: str | None = Field("acacia", title="Delivery")
    delivery_format: str | None = Field("files", title="Delivery Format")
    download_type: str | None = Field("vis", title="Download Type")
    user_pawsey_group: str = Field(..., title="User Pawsey Group")
    user_dug_group: str = Field(..., pattern="/^mwa (gleam|eor)$/i", title="User Dug Group")


class FieldError(BaseModel):
    """
    Field-specific validation error
    """

    field: str = Field(..., title="Field")
    """
    Field name that failed valiation
    """
    message: str = Field(..., title="Message")
    """
    Error message for this field
    """


class HealthResponse(BaseModel):
    """
    Health check response model
    """

    status: str = Field(..., title="Status")
    service: str = Field(..., title="Service")
    version: str = Field(..., title="Version")
    database: str = Field(..., title="Database")


class AbsThreshold(RootModel[float]):
    root: float = Field(0.001, ge=0.0, title="Abs Threshold")


class CleanThreshold(RootModel[float]):
    root: float = Field(..., ge=0.0, title="Clean Threshold")


class ImagingJobParams(BaseModel):
    """
    Parameters for image job submission
    """

    obs_id: int = Field(..., ge=888888889, title="Obs Id")
    job_type: str = Field(..., title="Job Type")
    delivery: Delivery | None = Field("acacia", title="Delivery", validate_default=True)
    delivery_format: DeliveryFormat | None = Field(
        "files", title="Delivery Format", validate_default=True
    )
    user_pawsey_group: str = Field(..., title="User Pawsey Group")
    user_dug_group: str = Field(..., pattern="/^mwa (gleam|eor)$/i", title="User Dug Group")
    apply_di_cal: bool | None = Field(True, title="Apply Di Cal")
    avg_time_res: AvgTimeRes | None = Field(2.0, title="Avg Time Res", validate_default=True)
    avg_freq_res: AvgFreqRes | None = Field(40.0, title="Avg Freq Res", validate_default=True)
    flag_edge_width: FlagEdgeWidth | None = Field(
        80.0, title="Flag Edge Width", validate_default=True
    )
    phase_center: str | None = Field("phase", title="Phase Center")
    custom_ra: float | None = Field(..., title="Custom Ra")
    custom_dec: float | None = Field(..., title="Custom Dec")
    image_size: int | None = Field(3072, title="Image Size")
    pixel_scale: float = Field(..., title="Pixel Scale")
    weighting: str | None = Field("briggs", title="Weighting")
    robust: float | None = Field(-0.5, title="Robust")
    clean_iterations: int | None = Field(100000, title="Clean Iterations")
    abs_threshold: AbsThreshold | None = Field(0.001, title="Abs Threshold", validate_default=True)
    clean_threshold: CleanThreshold | None = Field(..., title="Clean Threshold")
    auto_threshold: float | None = Field(0.5, title="Auto Threshold")
    nmiter: int | None = Field(10, title="Nmiter")
    mgain: float | None = Field(0.8, title="Mgain")
    auto_mask: int | None = Field(3, title="Auto Mask")
    apply_primary_beam: bool | None = Field(True, title="Apply Primary Beam")
    nwlayers: int | None = Field(..., title="Nwlayers")
    wstack_nwlayers: int | None = Field(..., title="Wstack Nwlayers")
    multiscale: bool | None = Field(False, title="Multiscale")
    uvw_min: float | None = Field(75, title="Uvw Min")
    uvw_max: float | None = Field(..., title="Uvw Max")
    join_polarizations: bool | None = Field(False, title="Join Polarizations")
    channels_out: int | None = Field(4, title="Channels Out")
    join_channels: bool | None = Field(True, title="Join Channels")
    pol: str | None = Field("XX,YY", title="Pol")
    input_mode: str | None = Field("raw", title="Input Mode")
    output_mode: str | None = Field("fits", title="Output Mode")


class TokenResponse(BaseModel):
    """
    Response model for token-issuing endpoints (login, refresh)
    """

    access_token: str = Field(..., title="Access Token")
    """
    JWT access token (also set in HTTP-only cookie)
    """
    refresh_token: str = Field(..., title="Refresh Token")
    """
    JWT refresh token (also set in HTTP-only cookie)
    """
    token_type: str | None = Field("bearer", title="Token Type")
    """
    Token type for Authorization header
    """


class UserLoginRequest(BaseModel):
    """
    Request model for login endpoint
    """

    username: str = Field(..., examples=["john_doe"], max_length=16, min_length=1, title="Username")
    """
    Username or email address
    """
    password: str = Field(
        ...,
        examples=["securePassword123!"],
        max_length=16,
        min_length=1,
        title="Password",
    )
    """
    User password
    """


class UserLogoutResponse(BaseModel):
    """
    Response model for logout endpoint
    """

    message: str | None = Field("Logged out successfully", title="Message")
    """
    success message
    """


class UserProfile(BaseModel):
    id: int = Field(..., title="Id")
    login: str = Field(..., title="Login")
    email: EmailStr | None = Field(None, title="Email")
    first_name: str | None = Field(None, title="First Name")
    last_name: str | None = Field(None, title="Last Name")
    is_superuser: bool | None = Field(False, title="Is Superuser")
    pawsey_group: str | None = Field(None, title="Pawsey Group")
    dug_group: str | None = Field(None, title="Dug Group")
    provider_id: int | None = Field(None, title="Provider Id")
    created: AwareDatetime | None = Field(None, title="Created")
    disabled: bool | None = Field(True, title="Disabled")
    confirmed: bool | None = Field(False, title="Confirmed")


class UserRegistrationRequest(BaseModel):
    """
    Request model for registration endpoint
    """

    username: str = Field(..., max_length=100, min_length=3, title="Username")
    password: str = Field(..., min_length=8, title="Password")
    retypepassword: str = Field(..., min_length=8, title="Retypepassword")
    firstname: str = Field(..., title="Firstname")
    lastname: str = Field(..., title="Lastname")
    email: EmailStr = Field(..., title="Email")
    affiliation: str = Field(..., title="Affiliation")
    orcid: str | None = Field(..., title="Orcid")
    confirmed: bool | None = Field(False, title="Confirmed")
    disabled: bool | None = Field(True, title="Disabled")
    subscribed_to_status_emails: bool | None = Field(False, title="Subscribed To Status Emails")
    provider_id: int | None = Field(1, title="Provider Id")


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")
    input: Any | None = Field(None, title="Input")
    ctx: dict[str, Any] | None = Field(None, title="Context")


class ToChannel(RootModel[int]):
    root: int = Field(..., ge=0, title="To Channel")


class VoltageJobParams(BaseModel):
    """
    Parameters for voltage job submission
    """

    obs_id: int = Field(..., ge=888888889, title="Obs Id")
    job_type: str = Field(..., title="Job Type")
    delivery: str | None = Field("scratch", title="Delivery")
    delivery_format: str | None = Field("files", title="Delivery Format")
    user_pawsey_group: str = Field(..., title="User Pawsey Group")
    offset: int = Field(..., title="Offset")
    duration: int = Field(..., ge=0, title="Duration")
    channel_range: bool | None = Field(False, title="Channel Range")
    from_channel: int | None = Field(None, title="From Channel")
    to_channel: ToChannel | None = Field(None, title="To Channel")


class ErrorResponse(BaseModel):
    """
    Standard error response structure for all ASVO API endpoints
    """

    error_code: str = Field(..., title="Error Code")
    """
    machine readable error code
    """
    message: str = Field(..., title="Message")
    """
    user friendly error message
    """
    detail: str | None = Field(None, title="Detail")
    """
    Additional technical detail
    """
    suggestion: str | None = Field(None, title="Suggestion")
    """
    Suggested resolution
    """
    field_errors: list[FieldError] | None = Field(None, title="Field Errors")
    """
    Field-specific validation errors
    """
    request_id: str | None = Field(None, title="Request Id")
    """
    Request ID for tracing
    """


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")
